import { ThemeProvider } from '@/components/theme-provider'
import { ApolloWrapper } from '@/lib/ApolloWrapper'
import { client } from '@/lib/client'
import { ApolloProvider } from '@apollo/client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				suppressHydrationWarning={true}
				suppressContentEditableWarning={true}
				className={inter.className}
			>
				<ApolloWrapper>
					<ThemeProvider
						attribute='class'
						defaultTheme='dark'
						enableSystem
						disableTransitionOnChange
					>
						{children}
					</ThemeProvider>
				</ApolloWrapper>
			</body>
		</html>
	)
}
